apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: spring-petclinic-spring-petclinic-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"petclinic-server","apps.kubernetes.io/name":"spring-petclinic","apps.tanzu.vmware.com/workload-type":"web"},"name":"spring-petclinic","namespace":"my-apps"},"spec":{"env":[{"name":"SPRING_PROFILES_ACTIVE","value":"mysql"},{"name":"JAVA_TOOL_OPTIONS","value":"-Dspring.devtools.restart.enabled=true -Dspring.devtools.restart.poll-interval=2s -Dspring.devtools.restart.quiet-period=1s -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005\n"}],"params":[{"name":"gitops_repository","value":"https://github.com/dapdelivery/spring-petclinic-dest-31-01-2024-04-45-34-801912475.git"},{"name":"gitops_repository_name","value":"spring-petclinic-dest-31-01-2024-04-45-34-801912475"}],"resources":{"limits":{"cpu":"4000m","memory":"1Gi"},"requests":{"cpu":"100m","memory":"1Gi"}},"serviceClaims":[{"name":"spring-petclinic-db","ref":{"apiVersion":"v1","kind":"Secret","name":"spring-petclinic-db"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/dapdelivery/spring-petclinic-31-01-2024-04-45-34-801912475.git"}}}}
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: petclinic-server
    apps.kubernetes.io/name: spring-petclinic
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: spring-petclinic
spec:
  name: spring-petclinic-db
  service:
    apiVersion: v1
    kind: Secret
    name: spring-petclinic-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: spring-petclinic

